extends: airbnb-base
plugins:
  - jasmine
env:
  jasmine: true
  browser: true
  es6: true
  node: true
rules:
  no-underscore-dangle: 0
  class-methods-use-this: 0
  no-param-reassign:
    - error
    - props: false
  no-new: 0
