---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 10

inputs:
- name: source_code
- name: dependency-cache

run:
  path: source_code/ci/scripts/test.sh
