#!/bin/bash

# find scripts in package.json
SCRIPTS=$(node -- <<END
  var scripts = require('./package.json').scripts;
  if (scripts != null) {
    Object.keys(scripts).forEach(function(script) {
      process.stdout.write(script+' ');
    });
  }
END
)

# Configure and build nodejs

# yarn build
if [[ " $SCRIPTS " =~ " build " ]]; then
  if [[ -f /app/yarn.lock ]]; then
    yarn build
  else
    npm run build
  fi
fi
