resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: sunlib/npm-gitcrypt
      tag: latest

resources:
  - name: source_code
    type: git
    source: &repo-source
      uri: https://github.com/sunny-b/WonderChat.git
      branch: master
      git_crypt_key: {{git_crypt_key}}
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json
  - name: image
    type: docker-image
    source:
      repository: sunlib/wonderchat
      username: sunlib
      password: {{password}}


jobs:
  - name: install
    plan:
      - get: source_code
        trigger: true
      - get: dependency-cache

  - name: test
    plan:
      - get: source_code
        trigger: true
        passed: [install]
      - get: dependency-cache
        passed: [install]
      - task: test
        file: source_code/ci/tasks/test.yml

  - name: update-image
    plan:
      - get: source_code
        passed: [test]
        trigger: true
      - get: dependency-cache
        passed: [test]
      - put: image
        params:
          build: source_code
          tag: source_code/.git/HEAD
          tag_as_latest: true

  - name: deploy-staging
    plan:
      - get: source_code
        passed: [update-image]
        trigger: true
      - task: deploy
        file: source_code/ci/tasks/deploy.yml
        params:
          SSH_USER: {{stage_ssh_user}}
          SSH_IP: 10.132.223.189
          SSH_KEY_PATH: source_code/ci/ssh.key

  - name: deploy-production
    plan:
      - get: source_code
        passed: [deploy-staging]
      - task: deploy
        file: source_code/ci/tasks/deploy.yml
        params:
          SSH_USER: {{prod_ssh_user}}
          SSH_IP: 10.132.245.101
          SSH_KEY_PATH: source_code/ci/ssh.key
