resources:
  - name: source_code
    type: git
    source:
      uri: https://github.com/sunny-b/WonderChat.git
      branch: master

  # - name: image
  #   type: docker-image
  #   source:
  #     repository: sunlib/wonderchat

jobs:
  - name: test
    plan:
      - get: source_code
        trigger: true
      - task: test-and-lint
        file: source_code/ci/tasks/test.yml
